### ISSUE TITLE
Minimap icons not working?

### ISSUE THREAD

**Issue by Siblingvv** [Qvin0000/ExileApiPlugins#18]
Dont see any mobs on large\mini map

**Comment by NoNick96** [comment]
Works fine for me.

**Comment by Siblingvv** [comment]
> 
> 
> Works fine for me.

can u upload ur version of plugin and resources(config, images)?

**Comment by NoNick96** [comment]
Here's my whole PoeHelper folder. I've changed Loader.exe name to Penguing.exe. 
https://www93.zippyshare.com/v/LSH0ofNv/file.html

**Comment by Siblingvv** [comment]
> 
> 
> Here's my whole PoeHelper folder. I've changed Loader.exe name to Penguing.exe.
> https://www93.zippyshare.com/v/LSH0ofNv/file.html

Oh, ur version really works... But i compile all with latest sources, wtf

**Comment by Siblingvv** [comment]
Oh, coz i idiot. I used minimapicins without iconbuilder....
